Settings:
  distance: 5
Messages:
  SexSucess: '&aВы успешно начали делать детей...'
  SexPartner: '&cТы хочешь выебать самого себя?'
  OfflinePlayer: '&cИгрок с кем ты хочешь к сожалению оффлайн.'
  Distance: '&cВы далеко от своего секс партнёра.'
  SelectPage: '&cКликай по кнопки:'
  BuyIgryshka: '&aВы купили игрушку..'
Random:
- '&aВсё прошло нормально.'
- '&cВы заразились спидом.'
Price:
  Buy: 200
Igryshka:
  Name: '&cИгрушка'
  Lore: '&7Кликай и играй ей..'
  Title: '&cВы начали игратьс игрушкой..'
  Title2: '&7о да...'
Help:
- '&c/sex call [Ник]&f- выебать своего партнёра.'
- '&c/sex buy&f- купить игришку.'